### PR TITLE
Login function error fixed

### PR DESCRIPTION
**Pull request by hasimyerlikaya**
Login function error fixed.
I added "params" json key to param_object

image

I added auto close client to the query function.

image

### CODE REVIEW

**Comment by Brandon-Gottshall** [comment]
Is this going to be merged sometime soon? This is seems pretty high urgency, and I personally have a team depending on it's functionality.

**Comment by hasimyerlikaya** [comment]
> Is this going to be merged sometime soon? This is seems pretty high urgency, and I personally have a team depending on it's functionality.

If you need to use it urgently, you can use the version in my account.


```
faunadb_http:
     git: https://github.com/hasimyerlikaya/faunadb-http-dart.git
```

**Comment by gavanitrate** [comment]
I will merge this soon (a day or two at most). @hasimyerlikaya The immediate shutdown seems out of scope for this PR but if more people think it is useful, we can consider another PR for it down the track. Thanks for the input btw 👍

**Comment by hasimyerlikaya** [comment]
You're welcome.

A few functions are missing, is it possible to add them?

- Merge
- CurrentIdentity
- HasCurrentIdentity
- CurrentToken
- HasCurrentToken

**Comment by Brandon-Gottshall** [comment]
> > Is this going to be merged sometime soon? This is seems pretty high urgency, and I personally have a team depending on it's functionality.
> 
> 
> 
> If you need to use it urgently, you can use the version in my account.
> 
> 
> 
> 
> 
> ```
> 
> faunadb_http:
> 
>      git: https://github.com/hasimyerlikaya/faunadb-http-dart.git
> 
> ```

@hasimyerlikaya Thanks for the suggestion. That's exactly what we're doing as of current.

**Comment by gavanitrate** [comment]
I will spend a bit of time on this today. I'll try to add those functions and merge this PR.

**Comment by hasimyerlikaya** [comment]
> I will spend a bit of time on this today. I'll try to add those functions and merge this PR.

Thank you.

**Comment by gavanitrate** [comment]
I have pushed version 0.9.0 which should solve the `Login` issue. I also added several FQL functions. @hasimyerlikaya I decided to not use this pull request but have added your handle to CONTRIBUTORS.md. I will look into adding further error support by using your changes as a base. Let me know if anyone runs into any more issues 🙂

**Comment by hasimyerlikaya** [comment]
> I have pushed version 0.9.0 which should solve the `Login` issue. I also added several FQL functions. @hasimyerlikaya I decided to not use this pull request but have added your handle to CONTRIBUTORS.md. I will look into adding further error support by using your changes as a base. Let me know if anyone runs into any more issues 🙂

Thank you. 

I added the error class by looking at the c# version, I have been using it for a long time and have not seen any problems. Better to have Class instead of Map.

**Pull request closed without merging**
